# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# start window numbering at 1
set -g base-index 1

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-[HJKL] without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# escape time (reported as low in nvim :checkhealth)
set-option -sg escape-time 10

# terminal
set -g default-terminal "screen-256color"
set -ga terminal-overrides ',*256col*:Tc'

###############
### VISUALS ###
###############

# prevent session names from being truncated
set -g status-left-length 40
set-option -g status-right "%d-%m-%Y %R"

# colours
set-option -g status-style fg=colour231,bg=colour240 #grey
set-window-option -g window-status-current-style fg=black,bg=colour214 #orange and default
set-window-option -g window-status-style fg=colour214,bg=default #base0 and default
