#!/bin/bash

echo zsh
echo ===
if [ `echo $SHELL` != "/usr/bin/zsh" ]; then
	sudo apt install zsh
	chsh -s $(which zsh)
	echo Please re-login to update shell settings
else
	echo Already running zsh
fi
echo

echo Oh My Zsh
echo =========
if [ ! -d ~/.oh-my-zsh ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	echo Installed Oh My Zsh. Please source .zshrc
else
	echo Already running Oh My Zsh
fi
echo

echo OhMyZsh plugins
echo ===============

if [ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]; then
	echo installing zsh-syntax-highlighting
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
else
	echo zsh-syntax-highlighting is already installed
fi
echo

echo Adding APT sources
echo ==================
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
echo

echo Updating APT
echo ============
sudo apt-get update
echo

echo APT packages
echo ============
sudo apt-get install git curl tmux neovim bat tldr jq ranger ssh chromium-browser gpt gpg fzf yarn tree highlight python3 python3-pip
sudo apt-get install cargo
echo

echo Python packages
echo ===============
pip3 install bpytop --upgrade
echo

echo Rust packages
echo =============
cargo install lsd git-delta
echo

echo Git configuration
echo =================
git config --global init.defaultBranch main
echo

echo asdf package manager
echo ====================
# asdf allows to manage different language-specific packages
# https://asdf-vm.com/#/core-manage-asdf
if [ ! -d ~/.asdf ]; then
	echo Installing asdf
	echo -------------
	git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
	echo Updating asdf
	echo -------------
	asdf update
	echo Installing asdf-nodejs plugin
	echo -----------------------------
	asdf plugin add nodejs
else
	echo Already have asdf installed
	echo ---------------------------
fi
echo

echo NodeJS runtime
echo ==============

if ! [ -x "$(command -v node)" ]; then
	echo In order to install nodejs runtime with asdf we need GPG keys of NodeJS team
	read -p "Do you want to import those keys? [y/N] " NODE_KEYS_REPLY

	if [[ $NODE_KEYS_REPLY =~ ^[Yy](es)$ ]]; then
		echo Please confirm the ones you want to import
		echo ------------------------------------------

# source: https://github.com/nodejs/node#release-keys
TEAM_EMAILS="bgriggs@redhat.com \
	adamzdanielle@gmail.com \
	jasnell@keybase.io \
	myles.borins@gmail.com \
	targos@protonmail.com \
	rlau@redhat.com \
	rod@vagg.org \
	ruben@bridgewater.de \
	ruyadorno@hotmail.com \
	shelley.vohr@gmail.com \
	cjihrig@gmail.com"

		for email in $TEAM_EMAILS; do
			yes | gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --search $email
		done
	else
		echo Skipping GPG keys import
	fi
	echo

	echo Installing node
	echo ---------------
	asdf install nodejs latest
	LATEST_NODE_VERSION=$(asdf list nodejs | tail -1)
	asdf global nodejs $LATEST_NODE_VERSION
	echo "global node version is set to $(node --version)"
	echo -------------------------------------------------
	echo
else
	echo "NodeJS is already installed - $(node --version)"
	echo -------------------------------------------------
fi
echo

echo SSH keys
echo ========

if find ~/.ssh -mindepth 1 | read; then
	echo Configured already
	echo ------------------
else
	echo No keys detected
	echo ----------------
	read -p "Do you want to create new keys? [y/N] " SSH_KEYS_REPLY

	if [[ $SSH_KEYS_REPLY =~ ^[Yy](es)$ ]]; then
		ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/provisioned_id_ed25519 -C "$(whoami)@$(hostname)"
		ssh-add $HOME/.ssh/provisioned_id_ed25519
		echo The new key is added to ssh-agent
		echo Add the following public key to your github/gitlab account
		cat $HOME/.ssh/provisioned_id_ed25519.pub
	fi
fi
echo

echo Bare repo for config files
echo ==========================

if [[ ! -d $HOME/.cfg ]]; then
	echo Cloning the repo
	echo ----------------
	echo If fails make sure the new SSH key is added to your Github profile

	git clone --bare git@github.com:valenber/dotfiles.git $HOME/.cfg

	read -p "Current config files will be overwritten. Continue? [y/N] " OVERWRITE_CONFIG_REPLY
	if [[ $OVERWRITE_CONFIG_REPLY =~ ^[Yy](es)$ ]]; then
		CFGIT="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
		echo `${CFGIT} checkout -f`
		echo `${CFGIT} branch -u origin/main`
		echo `${CFGIT} config --local status.showUntrackedFiles no`
		echo Restart shell for the changes to take place
	fi
else
	echo Already there
	echo -------------
fi
echo

echo Fira Code NF font
echo =================
if [[ ! -d /usr/share/fonts/opentype/firacode ]]; then
	echo Installing to /usr/share/fonts
	echo ------------------------------
	wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip -P $HOME/Downloads/
	unzip $HOME/Downloads/FiraCode.zip
	sudo cp $HOME/Downloads/FiraCode/Fira*.otf /usr/share/fonts/
	rm -rf $HOME/Downloads/FiraCode/
	rm $HOME/Downloads/FiraCode.zip
else
	echo Already installed
	echo -----------------
fi
echo

echo Ranger plugins
echo ==============
if [[ ! -d $HOME/.config/ranger/plugins/ranger_devicons ]]; then
	echo Installing devicons
	echo -------------------
	git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
else
	echo devicons plugin is already installed
	echo ------------------------------------
fi
echo

echo OneDark theme for gnome terminal
echo ================================
bash -c "$(curl -fsSL https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh)"
